export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth/login",
    REGISTER: "/api/auth/register",
    SESSION: "/api/auth/get-session",
    LOGOUT: "/api/auth/logout",
    GOOGLE: "/api/auth/login/google",
    ME: "/api/v1/auth/me",
    CHANGE_PASSWORD: "/api/v1/auth/change-password",
    VERIFY_EMAIL: "/api/v1/auth/verify-email",
    FORGET_PASSWORD: "/api/v1/auth/forget-password",
    RESET_PASSWORD: "/api/v1/auth/reset-password",
  },
  USERS: {
    ME: "/api/v1/users/me",
    PROFILE: "/api/v1/users/profile",
  },
  ADMINS: {
    STATS: "/api/v1/admins/stats",
    STAFF: "/api/v1/admins/staff",
    USERS: "/api/v1/admins/users",
    ROLES: "/api/v1/admins/roles",
    AUDIT_LOGS: "/api/v1/admins/audit-logs",
  },
  CATEGORIES: {
    LIST: "/api/v1/categories",
    TREE: "/api/v1/categories/tree",
    CREATE: "/api/v1/categories",
    UPDATE: (id: string) => `/api/v1/categories/${id}`,
    DELETE: (id: string) => `/api/v1/categories/${id}`,
    NOTICES: (categoryId: string) => `/api/v1/categories/${categoryId}/notice`,
  },
  PRODUCTS: {
    LIST: "/api/v1/products",
    CREATE: "/api/v1/products",
    UPDATE: (id: string) => `/api/v1/products/${id}`,
    DELETE: (id: string) => `/api/v1/products/${id}`,
    VARIANTS: "/api/v1/products/variants",
    CREATE_VARIANT: (productId: string) =>
      `/api/v1/products/${productId}/variants`,
    UPDATE_VARIANT: (id: string) => `/api/v1/products/variants/${id}`,
    DELETE_VARIANT: (id: string) => `/api/v1/products/variants/${id}`,
    UPDATE_PRICE: (variantId: string) =>
      `/api/v1/products/variants/${variantId}/price`,
    PRICE_HISTORY: (variantId: string) =>
      `/api/v1/products/variants/${variantId}/price-history`,
  },
  STORES: {
    LIST: "/api/v1/stores",
    CREATE: "/api/v1/stores",
    UPDATE: (id: string) => `/api/v1/stores/${id}`,
    DELETE: (id: string) => `/api/v1/stores/${id}`,
  },
  ORDERS: {
    LIST: "/api/v1/orders",
    CREATE: "/api/v1/orders",
    CANCEL: (id: string) => `/api/v1/orders/${id}/cancel`,
    STATUS: (id: string) => `/api/v1/orders/${id}/status`,
    TRACKING: (id: string) => `/api/v1/orders/${id}/tracking`,
  },
  PAYMENTS: {
    LIST: "/api/v1/payments",
    UPDATE: (id: string) => `/api/v1/payments/${id}`,
    BY_ORDER: (orderId: string) => `/api/v1/payments/order/${orderId}`,
  },
  CART: {
    MY: "/api/v1/cart/my",
    ITEMS: "/api/v1/cart/items",
    MERGE: "/api/v1/cart/merge",
  },
  EKYC: {
    MY: "/api/v1/ekyc/my",
    DOCUMENTS: "/api/v1/ekyc/my/documents",
    LIST: "/api/v1/ekyc",
    STATUS: (id: string) => `/api/v1/ekyc/${id}/status`,
  },
  NOTIFICATIONS: {
    MY: "/api/v1/notifications/my",
    UNREAD_COUNT: "/api/v1/notifications/my/unread-count",
    MARK_READ: (id: string) => `/api/v1/notifications/my/${id}/read`,
    MARK_ALL_READ: "/api/v1/notifications/my/read-all",
    CREATE: "/api/v1/notifications",
    DELETE: (id: string) => `/api/v1/notifications/${id}`,
  },
  ADDRESSES: {
    MY: "/api/v1/addresses/my",
    DIVISIONS: "/api/v1/addresses/divisions",
    DISTRICTS_BY_DIVISION: (divisionId: number) =>
      `/api/v1/addresses/divisions/${divisionId}/districts`,
    DISTRICTS: "/api/v1/addresses/districts",
    DEFAULT: (id: string) => `/api/v1/addresses/my/${id}/default`,
  },
  NEWS: {
    LIST: "/api/v1/news",
    CREATE: "/api/v1/news",
    UPDATE: (id: string) => `/api/v1/news/${id}`,
    DELETE: (id: string) => `/api/v1/news/${id}`,
  },
  BANNERS: {
    LIST: "/api/v1/banners",
    CREATE: "/api/v1/banners",
    UPDATE: (id: string) => `/api/v1/banners/${id}`,
    DELETE: (id: string) => `/api/v1/banners/${id}`,
  },
  BUYBACK_FEATURES: {
    LIST: "/api/v1/buyback-features",
    CREATE: "/api/v1/buyback-features",
    UPDATE: (id: string) => `/api/v1/buyback-features/${id}`,
    DELETE: (id: string) => `/api/v1/buyback-features/${id}`,
  },
} as const;
