export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  CONTACT: "/contact",
  PRODUCTS: "/products",
  STORES: "/stores",
  CATEGORIES: "/categories",

  USER: {
    DASHBOARD: "/user-dashboard",
    PROFILE: "/user-dashboard/profile",
    ORDERS: "/user-dashboard/orders",
    ADDRESSES: "/user-dashboard/addresses",
    EKYC: "/user-dashboard/ekyc",
    NOTIFICATIONS: "/user-dashboard/notifications",
    PAYMENTS: "/user-dashboard/payments",
  },

  ADMIN: {
    DASHBOARD: "/admin-dashboard",
    USERS: "/admin-dashboard/users",
    CATEGORIES: "/admin-dashboard/categories",
    PRODUCTS: "/admin-dashboard/products",
    STORES: "/admin-dashboard/stores",
    ORDERS: "/admin-dashboard/orders",
    PAYMENTS: "/admin-dashboard/payments",
    BANNERS: "/admin-dashboard/banners",
    NEWS: "/admin-dashboard/news",
    EKYC: "/admin-dashboard/ekyc",
    NOTIFICATIONS: "/admin-dashboard/notifications",
    ADDRESSES: "/admin-dashboard/addresses",
    REPORTS: "/admin-dashboard/reports",
    ANALYTICS: "/admin-dashboard/analytics",
    CART: "/admin-dashboard/cart",
    PROFILE: "/admin-dashboard/profile",
  },
} as const;
